/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContentStatus = IDL.Variant({
  'planned' : IDL.Null,
  'posted' : IDL.Null,
});
export const ContentType = IDL.Variant({
  'educational' : IDL.Null,
  'sales' : IDL.Null,
  'story' : IDL.Null,
});
export const ContentPlanItem = IDL.Record({
  'id' : IDL.Int32,
  'day' : IDL.Int32,
  'status' : ContentStatus,
  'title' : IDL.Text,
  'contentType' : ContentType,
  'description' : IDL.Text,
});
export const ContentGoal = IDL.Variant({
  'growth' : IDL.Null,
  'leads' : IDL.Null,
  'sales' : IDL.Null,
});
export const Platform = IDL.Variant({
  'instagram' : IDL.Null,
  'youtube' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'contentGoal' : ContentGoal,
  'platform' : Platform,
  'targetAudience' : IDL.Text,
  'niche' : IDL.Text,
});
export const Time = IDL.Int;
export const Hook = IDL.Record({
  'id' : IDL.Int32,
  'createdAt' : Time,
  'text' : IDL.Text,
});
export const Script = IDL.Record({
  'id' : IDL.Int32,
  'cta' : IDL.Text,
  'title' : IDL.Text,
  'hook' : IDL.Text,
  'createdAt' : Time,
  'mainContent' : IDL.Text,
});

export const idlService = IDL.Service({
  'createContentPlanItem' : IDL.Func(
      [IDL.Int32, ContentPlanItem],
      [IDL.Int32],
      [],
    ),
  'createOrUpdateUserProfile' : IDL.Func([UserProfile], [], []),
  'generateHook' : IDL.Func([IDL.Text], [IDL.Int32], []),
  'generateScript' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Int32],
      [],
    ),
  'getAllContentPlanItems' : IDL.Func(
      [],
      [IDL.Vec(ContentPlanItem)],
      ['query'],
    ),
  'getAllHooks' : IDL.Func([], [IDL.Vec(Hook)], ['query']),
  'getAllScripts' : IDL.Func([], [IDL.Vec(Script)], ['query']),
  'getUserProfile' : IDL.Func([], [UserProfile], ['query']),
  'updateContentPlanItemStatus' : IDL.Func([IDL.Int32, ContentStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContentStatus = IDL.Variant({
    'planned' : IDL.Null,
    'posted' : IDL.Null,
  });
  const ContentType = IDL.Variant({
    'educational' : IDL.Null,
    'sales' : IDL.Null,
    'story' : IDL.Null,
  });
  const ContentPlanItem = IDL.Record({
    'id' : IDL.Int32,
    'day' : IDL.Int32,
    'status' : ContentStatus,
    'title' : IDL.Text,
    'contentType' : ContentType,
    'description' : IDL.Text,
  });
  const ContentGoal = IDL.Variant({
    'growth' : IDL.Null,
    'leads' : IDL.Null,
    'sales' : IDL.Null,
  });
  const Platform = IDL.Variant({
    'instagram' : IDL.Null,
    'youtube' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'contentGoal' : ContentGoal,
    'platform' : Platform,
    'targetAudience' : IDL.Text,
    'niche' : IDL.Text,
  });
  const Time = IDL.Int;
  const Hook = IDL.Record({
    'id' : IDL.Int32,
    'createdAt' : Time,
    'text' : IDL.Text,
  });
  const Script = IDL.Record({
    'id' : IDL.Int32,
    'cta' : IDL.Text,
    'title' : IDL.Text,
    'hook' : IDL.Text,
    'createdAt' : Time,
    'mainContent' : IDL.Text,
  });
  
  return IDL.Service({
    'createContentPlanItem' : IDL.Func(
        [IDL.Int32, ContentPlanItem],
        [IDL.Int32],
        [],
      ),
    'createOrUpdateUserProfile' : IDL.Func([UserProfile], [], []),
    'generateHook' : IDL.Func([IDL.Text], [IDL.Int32], []),
    'generateScript' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Int32],
        [],
      ),
    'getAllContentPlanItems' : IDL.Func(
        [],
        [IDL.Vec(ContentPlanItem)],
        ['query'],
      ),
    'getAllHooks' : IDL.Func([], [IDL.Vec(Hook)], ['query']),
    'getAllScripts' : IDL.Func([], [IDL.Vec(Script)], ['query']),
    'getUserProfile' : IDL.Func([], [UserProfile], ['query']),
    'updateContentPlanItemStatus' : IDL.Func(
        [IDL.Int32, ContentStatus],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };