/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ContentGoal = { 'growth' : null } |
  { 'leads' : null } |
  { 'sales' : null };
export interface ContentPlanItem {
  'id' : number,
  'day' : number,
  'status' : ContentStatus,
  'title' : string,
  'contentType' : ContentType,
  'description' : string,
}
export type ContentStatus = { 'planned' : null } |
  { 'posted' : null };
export type ContentType = { 'educational' : null } |
  { 'sales' : null } |
  { 'story' : null };
export interface Hook { 'id' : number, 'createdAt' : Time, 'text' : string }
export type Platform = { 'instagram' : null } |
  { 'youtube' : null };
export interface Script {
  'id' : number,
  'cta' : string,
  'title' : string,
  'hook' : string,
  'createdAt' : Time,
  'mainContent' : string,
}
export type Time = bigint;
export interface UserProfile {
  'contentGoal' : ContentGoal,
  'platform' : Platform,
  'targetAudience' : string,
  'niche' : string,
}
export interface _SERVICE {
  'createContentPlanItem' : ActorMethod<[number, ContentPlanItem], number>,
  'createOrUpdateUserProfile' : ActorMethod<[UserProfile], undefined>,
  'generateHook' : ActorMethod<[string], number>,
  'generateScript' : ActorMethod<[string, string, string, string], number>,
  'getAllContentPlanItems' : ActorMethod<[], Array<ContentPlanItem>>,
  'getAllHooks' : ActorMethod<[], Array<Hook>>,
  'getAllScripts' : ActorMethod<[], Array<Script>>,
  'getUserProfile' : ActorMethod<[], UserProfile>,
  'updateContentPlanItemStatus' : ActorMethod<
    [number, ContentStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];