/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Script {
    id: number;
    cta: string;
    title: string;
    hook: string;
    createdAt: Time;
    mainContent: string;
}
export interface Hook {
    id: number;
    createdAt: Time;
    text: string;
}
export interface ContentPlanItem {
    id: number;
    day: number;
    status: ContentStatus;
    title: string;
    contentType: ContentType;
    description: string;
}
export interface UserProfile {
    contentGoal: ContentGoal;
    platform: Platform;
    targetAudience: string;
    niche: string;
}
export enum ContentGoal {
    growth = "growth",
    leads = "leads",
    sales = "sales"
}
export enum ContentStatus {
    planned = "planned",
    posted = "posted"
}
export enum ContentType {
    educational = "educational",
    sales = "sales",
    story = "story"
}
export enum Platform {
    instagram = "instagram",
    youtube = "youtube"
}
export interface backendInterface {
    createContentPlanItem(day: number, contentPlanItem: ContentPlanItem): Promise<number>;
    createOrUpdateUserProfile(profile: UserProfile): Promise<void>;
    generateHook(text: string): Promise<number>;
    generateScript(title: string, hookText: string, mainContent: string, cta: string): Promise<number>;
    getAllContentPlanItems(): Promise<Array<ContentPlanItem>>;
    getAllHooks(): Promise<Array<Hook>>;
    getAllScripts(): Promise<Array<Script>>;
    getUserProfile(): Promise<UserProfile>;
    updateContentPlanItemStatus(id: number, status: ContentStatus): Promise<void>;
}
import type { ContentGoal as _ContentGoal, ContentPlanItem as _ContentPlanItem, ContentStatus as _ContentStatus, ContentType as _ContentType, Platform as _Platform, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createContentPlanItem(arg0: number, arg1: ContentPlanItem): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.createContentPlanItem(arg0, to_candid_ContentPlanItem_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createContentPlanItem(arg0, to_candid_ContentPlanItem_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createOrUpdateUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateUserProfile(to_candid_UserProfile_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateUserProfile(to_candid_UserProfile_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async generateHook(arg0: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.generateHook(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateHook(arg0);
            return result;
        }
    }
    async generateScript(arg0: string, arg1: string, arg2: string, arg3: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.generateScript(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateScript(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async getAllContentPlanItems(): Promise<Array<ContentPlanItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContentPlanItems();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContentPlanItems();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllHooks(): Promise<Array<Hook>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHooks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHooks();
            return result;
        }
    }
    async getAllScripts(): Promise<Array<Script>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllScripts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllScripts();
            return result;
        }
    }
    async getUserProfile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return from_candid_UserProfile_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return from_candid_UserProfile_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateContentPlanItemStatus(arg0: number, arg1: ContentStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContentPlanItemStatus(arg0, to_candid_ContentStatus_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContentPlanItemStatus(arg0, to_candid_ContentStatus_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ContentGoal_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContentGoal): ContentGoal {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_ContentPlanItem_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContentPlanItem): ContentPlanItem {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_ContentStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContentStatus): ContentStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_ContentType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContentType): ContentType {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Platform_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Platform): Platform {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: number;
    day: number;
    status: _ContentStatus;
    title: string;
    contentType: _ContentType;
    description: string;
}): {
    id: number;
    day: number;
    status: ContentStatus;
    title: string;
    contentType: ContentType;
    description: string;
} {
    return {
        id: value.id,
        day: value.day,
        status: from_candid_ContentStatus_n16(_uploadFile, _downloadFile, value.status),
        title: value.title,
        contentType: from_candid_ContentType_n18(_uploadFile, _downloadFile, value.contentType),
        description: value.description
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contentGoal: _ContentGoal;
    platform: _Platform;
    targetAudience: string;
    niche: string;
}): {
    contentGoal: ContentGoal;
    platform: Platform;
    targetAudience: string;
    niche: string;
} {
    return {
        contentGoal: from_candid_ContentGoal_n22(_uploadFile, _downloadFile, value.contentGoal),
        platform: from_candid_Platform_n24(_uploadFile, _downloadFile, value.platform),
        targetAudience: value.targetAudience,
        niche: value.niche
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    planned: null;
} | {
    posted: null;
}): ContentStatus {
    return "planned" in value ? ContentStatus.planned : "posted" in value ? ContentStatus.posted : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    educational: null;
} | {
    sales: null;
} | {
    story: null;
}): ContentType {
    return "educational" in value ? ContentType.educational : "sales" in value ? ContentType.sales : "story" in value ? ContentType.story : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    growth: null;
} | {
    leads: null;
} | {
    sales: null;
}): ContentGoal {
    return "growth" in value ? ContentGoal.growth : "leads" in value ? ContentGoal.leads : "sales" in value ? ContentGoal.sales : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    instagram: null;
} | {
    youtube: null;
}): Platform {
    return "instagram" in value ? Platform.instagram : "youtube" in value ? Platform.youtube : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContentPlanItem>): Array<ContentPlanItem> {
    return value.map((x)=>from_candid_ContentPlanItem_n14(_uploadFile, _downloadFile, x));
}
function to_candid_ContentGoal_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentGoal): _ContentGoal {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_ContentPlanItem_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentPlanItem): _ContentPlanItem {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_ContentStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentStatus): _ContentStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_ContentType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentType): _ContentType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Platform_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Platform): _Platform {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: number;
    day: number;
    status: ContentStatus;
    title: string;
    contentType: ContentType;
    description: string;
}): {
    id: number;
    day: number;
    status: _ContentStatus;
    title: string;
    contentType: _ContentType;
    description: string;
} {
    return {
        id: value.id,
        day: value.day,
        status: to_candid_ContentStatus_n3(_uploadFile, _downloadFile, value.status),
        title: value.title,
        contentType: to_candid_ContentType_n5(_uploadFile, _downloadFile, value.contentType),
        description: value.description
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contentGoal: ContentGoal;
    platform: Platform;
    targetAudience: string;
    niche: string;
}): {
    contentGoal: _ContentGoal;
    platform: _Platform;
    targetAudience: string;
    niche: string;
} {
    return {
        contentGoal: to_candid_ContentGoal_n9(_uploadFile, _downloadFile, value.contentGoal),
        platform: to_candid_Platform_n11(_uploadFile, _downloadFile, value.platform),
        targetAudience: value.targetAudience,
        niche: value.niche
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentGoal): {
    growth: null;
} | {
    leads: null;
} | {
    sales: null;
} {
    return value == ContentGoal.growth ? {
        growth: null
    } : value == ContentGoal.leads ? {
        leads: null
    } : value == ContentGoal.sales ? {
        sales: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Platform): {
    instagram: null;
} | {
    youtube: null;
} {
    return value == Platform.instagram ? {
        instagram: null
    } : value == Platform.youtube ? {
        youtube: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentStatus): {
    planned: null;
} | {
    posted: null;
} {
    return value == ContentStatus.planned ? {
        planned: null
    } : value == ContentStatus.posted ? {
        posted: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentType): {
    educational: null;
} | {
    sales: null;
} | {
    story: null;
} {
    return value == ContentType.educational ? {
        educational: null
    } : value == ContentType.sales ? {
        sales: null
    } : value == ContentType.story ? {
        story: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
